version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test

  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Project
          command: npm run build

  # deploy:
  #   docker:
  #     - image: circleci/node:14
  #   steps:
  #     - checkout
  #     - run:
  #         name: Install Heroku CLI
  #         command: curl https://cli-assets.heroku.com/install.sh | sh
  #     - run:
  #         name: Deploy to Heroku
  #         command: |
  #           echo "machine api.heroku.com" >> ~/.netrc
  #           echo "  login $HEROKU_EMAIL" >> ~/.netrc
  #           echo "  password $HEROKU_API_KEY" >> ~/.netrc
  #           chmod 600 ~/.netrc
  #           git remote add heroku https://git.heroku.com/$HEROKU_APP_NAME.git
  #           git push heroku main

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      # - deploy:
      #     requires:
      #       - build
