version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test

  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Project
          command: npm run build

  deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Render CLI
          command: |
            curl -sSL https://render.com/install.sh | bash

      - run:
          name: Deploy to Render
          command: |
            render login --email yavuz.mersin@hotmail.com --password yavuzhavva2001
            render deploy --name my-render-app --path ./dist

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
                - feature/*
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - main
                - feature/*
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
